CREATE DATABASE [E-Banking]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'E-Banking', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\E-Banking.mdf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'E-Banking_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\E-Banking_log.ldf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
 WITH LEDGER = OFF
GO
ALTER DATABASE [E-Banking] SET COMPATIBILITY_LEVEL = 160
GO
ALTER DATABASE [E-Banking] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [E-Banking] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [E-Banking] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [E-Banking] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [E-Banking] SET ARITHABORT OFF 
GO
ALTER DATABASE [E-Banking] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [E-Banking] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [E-Banking] SET AUTO_CREATE_STATISTICS ON(INCREMENTAL = OFF)
GO
ALTER DATABASE [E-Banking] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [E-Banking] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [E-Banking] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [E-Banking] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [E-Banking] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [E-Banking] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [E-Banking] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [E-Banking] SET  DISABLE_BROKER 
GO
ALTER DATABASE [E-Banking] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [E-Banking] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [E-Banking] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [E-Banking] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [E-Banking] SET  READ_WRITE 
GO
ALTER DATABASE [E-Banking] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [E-Banking] SET  MULTI_USER 
GO
ALTER DATABASE [E-Banking] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [E-Banking] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [E-Banking] SET DELAYED_DURABILITY = DISABLED 
GO
USE [E-Banking]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = On;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = Primary;
GO
USE [E-Banking]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [E-Banking] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO
